import { defineConfig } from 'rolldown';

export default defineConfig([
  {
    input: 'src/index.ts',
    output: {
      dir: 'dist',
      format: 'esm',
      sourcemap: true,
    },
    external: [
      'react',
      'react-dom',
      'next',
      'drizzle-orm',
      '@refinedev/core',
      '@refinedev/react-table',
      '@tanstack/react-table',
      'refine-sqlx',
      '@events/ui',
      '@events/ui/components/*',
      '@events/ui/lib/*',
    ],
    platform: 'neutral',
  },
  {
    input: 'src/server/index.ts',
    output: {
      dir: 'dist/server',
      format: 'esm',
      sourcemap: true,
    },
    external: [
      'react',
      'react-dom',
      'next',
      'drizzle-orm',
      '@refinedev/core',
      '@refinedev/react-table',
      '@tanstack/react-table',
      'refine-sqlx',
      '@events/ui',
      '@events/ui/components/*',
      '@events/ui/lib/*',
    ],
    platform: 'node',
  },
  {
    input: 'src/client/index.ts',
    output: {
      dir: 'dist/client',
      format: 'esm',
      sourcemap: true,
    },
    external: [
      'react',
      'react-dom',
      'next',
      'drizzle-orm',
      '@refinedev/core',
      '@refinedev/react-table',
      '@tanstack/react-table',
      'refine-sqlx',
      '@events/ui',
      '@events/ui/components/*',
      '@events/ui/lib/*',
    ],
    platform: 'browser',
  },
  {
    input: 'src/components/index.ts',
    output: {
      dir: 'dist/components',
      format: 'esm',
      sourcemap: true,
      banner: '"use client";',
    },
    external: [
      'react',
      'react-dom',
      'next',
      'drizzle-orm',
      '@refinedev/core',
      '@refinedev/react-table',
      '@refinedev/nextjs-router',
      '@tanstack/react-table',
      'refine-sqlx',
      '@events/ui',
      '@events/ui/components/*',
      '@events/ui/lib/*',
      'lucide-react',
      'radix-ui',
      '@radix-ui/*',
      'use-sync-external-store',
      'cmdk',
      'date-fns',
      'react-day-picker',
      'tailwind-merge',
      'class-variance-authority',
      'clsx',
    ],
    platform: 'browser',
  },
]);
